name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sandesh2057/ilovedevops:v1 .

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push sandesh2057/ilovedevops:v1

      - name: Set up Minikube
        uses: medyagh/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.32.0'
          kubernetes version: 'v1.28.3'
          driver: docker

      - name: Deploy to Kubernetes
        run: |
          echo "Applying Kubernetes Deployment..."
          kubectl apply -f k8s/deploy.yaml
          echo "Applying Kubernetes Service..."
          kubectl apply -f k8s/service.yaml

      - name: Check Deployment status
        run: |
          kubectl rollout status deployment/ilovedevops

